### ISSUE TITLE
Infinite loop loop if key does not exist

### ISSUE THREAD

**Issue by ostcar** [funkybob/puppy#2]
If (for any reason) a key does not exist in redis but the puppet-status key, then there will be an infinite loop: https://github.com/funkybob/puppy/blob/master/puppy/redis.py#L62

What I am trying to do is using redis as a cache. Therefore I have to delete a key when the content changes.

One solution would be to create a method cache.pdelete that deletes the key and the puppet status key. But this does not solve the problem if there is a puppet status key for an non existing key for another reason.

**Comment by funkybob** [comment]
Given the status key always has a timeout, how can we wind up in an infinite loop?

https://github.com/funkybob/puppy/blob/master/puppy/redis.py#L36
https://github.com/funkybob/puppy/blob/master/puppy/redis.py#L53

I'm not averse to the idea of a pdel... there used to be a pset, but I believe it was broken, so it got removed.

**Comment by ostcar** [comment]
When you create a key with pget for the first time, the state_key gets a timeout of 5 minutes, when there is not any other default value: https://github.com/django/django/blob/master/django/core/cache/backends/base.py#L54

If you now delete the original key but not the state_key, you will end up in this loop for 5 minutes: https://github.com/funkybob/puppy/blob/master/puppy/redis.py#L62

For a webserver, that is as nearly infinite.

I implemented you function in another way, that does only need the status keys for the time the key is updated. So the original key can be deleted using the normal redis functions:
https://gist.github.com/ostcar/b42dbe11a13ac0e7f88e

**Comment by funkybob** [comment]
Originally the state_key is created with a 30 second [default, overridable] timeout:
https://github.com/funkybob/puppy/blob/master/puppy/redis.py#L36

Then it gets set with the requested content timeout [overridable, defaults to cache default]:
https://github.com/funkybob/puppy/blob/master/puppy/redis.py#L44
https://github.com/funkybob/puppy/blob/master/puppy/redis.py#L54

So the only way it winds up being 5 minutes is if you don't specify your own timeout when calling pget(), and you don't change the default timeout of your cache.

In fact, this is just the same as normal use of the django cache api... if you don't specify the timeout you want, you get 5 minutes.

I'll review your code [which, indeed, looks simpler] and see if there are any hazardous states.

**Comment by ostcar** [comment]
**updated**

Which value do you use as timeout? That is the time any client has to wait, before the original value is created again And also that is the time, any client get stack in line 63. I use 24 \* 60 \* 60.

There is one known hazardous state in my code. If the callback() needs more time then update_time, then one other worker also calls the callback. So if callback() needs one minute and update_time is 6 seconds, then 10 workers call callback() at the same time. But if you set a to high update_time value and for any reason the finally code block is not called, then the value will not be created until the state_key is expired.

**Comment by funkybob** [comment]
I use whatever timeout you pass to the pget() method:

https://github.com/funkybob/puppy/blob/master/puppy/redis.py#L22

if you don't pass one, I fallback to the same algorithm as Django's cache API:

https://github.com/funkybob/puppy/blob/master/puppy/redis.py#L43

So, if you don't pass one to pget(), it will default to the default timeout for the cache config... and that is 300 seconds.

I don't force any timeout value on you -- you get to control it just as with the rest of Django's cache API.

In my code, the update_time is the time expected for regeneration, and _2_ times that is allowed:

https://github.com/funkybob/puppy/blob/master/puppy/redis.py#L46

That way, if the initial attempt fails, and the next attempt works, you probably made it in time.  In the mean time, you're still serving the old value. [Except for the fully expired case]
